-- 코드를 입력하세요
SELECT FI.FLAVOR
FROM FIRST_HALF FI
    LEFT OUTER JOIN ICECREAM_INFO II
    ON FI.FLAVOR = II.FLAVOR
WHERE FI.TOTAL_ORDER > 3000
AND II.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC