SELECT HISTORY_ID
    , CAR_ID
    , TO_CHAR(START_DATE, 'YYYY-MM-DD') AS START_DATE
    , TO_CHAR(END_DATE, 'YYYY-MM-DD') AS END_DATE
    , CASE
    -- 대여일에 시작일, 반납일이 포함되기 때문에 30이 아니라 29를 더함
    WHEN START_DATE + 29 <= END_DATE
        THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYYMM') = '202209'
ORDER BY HISTORY_ID DESC