SELECT OU.ANIMAL_ID, OU.NAME
FROM ANIMAL_OUTS OU
LEFT JOIN ANIMAL_INS INS
ON OU.ANIMAL_ID = INS.ANIMAL_ID
-- 두 테이블을 JOIN한 뒤 NULL인 데이터를 찾으면 매칭되지 않은 데이터만 필터링 됨
WHERE INS.ANIMAL_ID IS NULL
ORDER BY OU.ANIMAL_ID