-- 코드를 입력하세요
SELECT MEMBER_ID
, MEMBER_NAME
, GENDER
, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'
-- 생일이 3월 달인 사람 찾기
AND GENDER = 'W'
AND TLNO IS NOT NULL
-- 전화번호가 NULL 인 사람은 제외
ORDER BY MEMBER_ID