SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
-- 숫자를 비교할 것이기 때문에 TO_NUMBER를 해줘야 함
WHERE TO_NUMBER(TO_CHAR(DATETIME,'HH24')) BETWEEN 09 AND 19
GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))
ORDER BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))