SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE TO_CHAR(H.START_DATE, 'YYYY-MM-DD') >= '2022-10-01'
AND C.CAR_TYPE = '세단'
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;