SELECT P.TITLE, P.BOARD_ID, C.REPLY_ID, C.WRITER_ID, C.CONTENTS, TO_CHAR(C.CREATED_DATE, 'YYYY-MM-DD') created_date
-- 출력 형식을 맞추기 위해 to_char 사용
FROM USED_GOODS_BOARD P, USED_GOODS_REPLY C
-- 테이블 이름 AS
WHERE P.BOARD_ID = C.BOARD_ID
-- 두 개의 테이블 연결
AND P.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
-- 정해진 기한 내의 데이터만을 조회
ORDER BY C.CREATED_DATE, P.TITLE
-- 정렬 조건 주기